"""add_candidate_enums

Revision ID: 28d2151a6a52
Revises: ca033550e355
Create Date: 2026-07-15 10:14:28.130394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28d2151a6a52'
down_revision: Union[str, None] = 'ca033550e355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'deployment_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('onsite', 'hybrid', 'remote', name='locationtypeenum'),
               existing_nullable=False,
               postgresql_using="deployment_type::locationtypeenum")
    
    op.drop_column('candidates', 'engagement_types')
    op.add_column('candidates', sa.Column('engagement_types', postgresql.ARRAY(sa.Enum('full_time', 'c2c', 'c2h', name='engagementtypeenum')), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'engagement_types')
    op.add_column('candidates', sa.Column('engagement_types', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    
    op.alter_column('candidates', 'deployment_type',
               existing_type=sa.Enum('onsite', 'hybrid', 'remote', name='locationtypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
