"""add_password_reset_to_otp_purpose

Revision ID: 33b4d64c93f8
Revises: 6c54856eb989
Create Date: 2026-07-14 11:48:02.716925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33b4d64c93f8'
down_revision: Union[str, None] = '6c54856eb989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE otppurposeenum ADD VALUE 'password_reset'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
