"""initial_schema_with_appropriate_types

Revision ID: 354267ae157b
Revises: 
Create Date: 2026-07-14 10:50:51.962545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = '354267ae157b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('domain_score', sa.Float(), nullable=False),
    sa.Column('project_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('improvement_areas', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', app.models.base.EmailField(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'vendor', name='roleenum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('active', 'locked', 'suspended', 'deleted', name='accountstatusenum'), nullable=False),
    sa.Column('registration_step', sa.Enum('otp_pending', 'profile_pending', 'subscription_pending', 'completed', name='registrationstepenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('client_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('website_url', app.models.base.URLField(length=2048), nullable=False),
    sa.Column('company_email', app.models.base.EmailField(length=255), nullable=False),
    sa.Column('poc_name', sa.String(length=255), nullable=False),
    sa.Column('poc_phone', sa.BigInteger(), nullable=False),
    sa.Column('poc_email', app.models.base.EmailField(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('about_summary', app.models.base.RichTextField(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('twitter_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('instagram_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('current_plan', sa.String(length=50), nullable=True),
    sa.Column('plan_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.Enum('jd', 'cv', name='documenttypeenum'), nullable=False),
    sa.Column('file_url', app.models.base.URLField(length=2048), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', app.models.base.EmailField(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('registration', 'login', 'resend', name='otppurposeenum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('requested_ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('replaced_by_token_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.Enum('free_trial', 'paid', name='subscriptionplanenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatusenum'), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('vendor_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('website_url', app.models.base.URLField(length=2048), nullable=False),
    sa.Column('company_email', app.models.base.EmailField(length=255), nullable=False),
    sa.Column('poc_name', sa.String(length=255), nullable=False),
    sa.Column('poc_phone', sa.BigInteger(), nullable=False),
    sa.Column('poc_email', app.models.base.EmailField(length=255), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('about_summary', app.models.base.RichTextField(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('has_labour_compliance', sa.Boolean(), nullable=False),
    sa.Column('pf_registered', sa.Boolean(), nullable=False),
    sa.Column('esic_registered', sa.Boolean(), nullable=False),
    sa.Column('gmc_registered', sa.Boolean(), nullable=False),
    sa.Column('fte_count', sa.Integer(), nullable=True),
    sa.Column('vendor_model', sa.JSON(), nullable=True),
    sa.Column('compliance_checklist', sa.JSON(), nullable=True),
    sa.Column('declaration_confirmed', sa.Boolean(), nullable=True),
    sa.Column('linkedin_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('twitter_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('instagram_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('facebook_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('current_plan', sa.String(length=50), nullable=True),
    sa.Column('plan_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('total_experience', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('deployment_type', sa.String(length=50), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('engagement_types', sa.JSON(), nullable=False),
    sa.Column('primary_skills', sa.JSON(), nullable=False),
    sa.Column('secondary_skills', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('linkedin_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('github_url', app.models.base.URLField(length=2048), nullable=True),
    sa.Column('rate_currency', sa.String(length=10), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('rate_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_vendor_id'), 'candidates', ['vendor_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('interview_rounds', sa.Integer(), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('experience', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('budget_currency', sa.String(length=10), nullable=False),
    sa.Column('budget_type', sa.String(length=50), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('jd_summary', app.models.base.RichTextField(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('project_duration', sa.String(length=100), nullable=True),
    sa.Column('compliance_required', sa.Boolean(), nullable=False),
    sa.Column('compliance_requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_table('candidate_educations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('institute', sa.String(length=255), nullable=False),
    sa.Column('passing_year', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_educations_candidate_id'), 'candidate_educations', ['candidate_id'], unique=False)
    op.create_table('candidate_project_experiences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_project_experiences_candidate_id'), 'candidate_project_experiences', ['candidate_id'], unique=False)
    op.create_table('candidate_work_experiences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_work_experiences_candidate_id'), 'candidate_work_experiences', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_work_experiences_candidate_id'), table_name='candidate_work_experiences')
    op.drop_table('candidate_work_experiences')
    op.drop_index(op.f('ix_candidate_project_experiences_candidate_id'), table_name='candidate_project_experiences')
    op.drop_table('candidate_project_experiences')
    op.drop_index(op.f('ix_candidate_educations_candidate_id'), table_name='candidate_educations')
    op.drop_table('candidate_educations')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidates_vendor_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('vendor_profiles')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ai_scores')
    # ### end Alembic commands ###
