"""make_user_id_nullable_in_otp

Revision ID: 6c54856eb989
Revises: 354267ae157b
Create Date: 2026-07-14 11:42:03.148339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c54856eb989'
down_revision: Union[str, None] = '354267ae157b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_verifications', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
