"""add_jobs_and_candidates

Revision ID: 7d22163290f4
Revises: ed162651c0ed
Create Date: 2026-07-10 15:19:56.336455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d22163290f4'
down_revision: Union[str, None] = 'ed162651c0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('total_experience', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('deployment_type', sa.String(length=50), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=False),
    sa.Column('engagement_types', sa.JSON(), nullable=False),
    sa.Column('primary_skills', sa.JSON(), nullable=False),
    sa.Column('secondary_skills', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('rate_currency', sa.String(length=10), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('rate_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_vendor_id'), 'candidates', ['vendor_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('interview_rounds', sa.Integer(), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('experience', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('budget_currency', sa.String(length=10), nullable=False),
    sa.Column('budget_type', sa.String(length=50), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('jd_summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('project_duration', sa.String(length=100), nullable=True),
    sa.Column('compliance_required', sa.Boolean(), nullable=False),
    sa.Column('compliance_requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_table('candidate_educations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('institute', sa.String(length=255), nullable=False),
    sa.Column('passing_year', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_educations_candidate_id'), 'candidate_educations', ['candidate_id'], unique=False)
    op.create_table('candidate_project_experiences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_project_experiences_candidate_id'), 'candidate_project_experiences', ['candidate_id'], unique=False)
    op.create_table('candidate_work_experiences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_work_experiences_candidate_id'), 'candidate_work_experiences', ['candidate_id'], unique=False)
    op.add_column('vendor_profiles', sa.Column('vendor_model', sa.JSON(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('compliance_checklist', sa.JSON(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('declaration_confirmed', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'declaration_confirmed')
    op.drop_column('vendor_profiles', 'compliance_checklist')
    op.drop_column('vendor_profiles', 'vendor_model')
    op.drop_index(op.f('ix_candidate_work_experiences_candidate_id'), table_name='candidate_work_experiences')
    op.drop_table('candidate_work_experiences')
    op.drop_index(op.f('ix_candidate_project_experiences_candidate_id'), table_name='candidate_project_experiences')
    op.drop_table('candidate_project_experiences')
    op.drop_index(op.f('ix_candidate_educations_candidate_id'), table_name='candidate_educations')
    op.drop_table('candidate_educations')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidates_vendor_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
