"""initial

Revision ID: ed162651c0ed
Revises: 
Create Date: 2026-07-10 10:42:16.371032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed162651c0ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('domain_score', sa.Float(), nullable=False),
    sa.Column('project_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('improvement_areas', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('client', 'vendor', name='roleenum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('client_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=False),
    sa.Column('poc_name', sa.String(length=255), nullable=False),
    sa.Column('poc_phone', sa.String(length=20), nullable=False),
    sa.Column('poc_email', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('about_summary', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('current_plan', sa.String(length=50), nullable=True),
    sa.Column('plan_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('requested_ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('replaced_by_token_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('vendor_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=False),
    sa.Column('poc_name', sa.String(length=255), nullable=False),
    sa.Column('poc_phone', sa.String(length=20), nullable=False),
    sa.Column('poc_email', sa.String(length=255), nullable=False),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('about_summary', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('has_labour_compliance', sa.Boolean(), nullable=False),
    sa.Column('pf_registered', sa.Boolean(), nullable=False),
    sa.Column('esic_registered', sa.Boolean(), nullable=False),
    sa.Column('gmc_registered', sa.Boolean(), nullable=False),
    sa.Column('fte_count', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('current_plan', sa.String(length=50), nullable=True),
    sa.Column('plan_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_profiles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_table('ai_scores')
    # ### end Alembic commands ###
